### PR TITLE
chan_pjsip: Fix deadlock when endpoint set_var uses PJSIP_HEADER

### LINKED ISSUE #1872: [bug]:  Deadlock in chan_pjsip_new when endpoint set_var invokes PJSIP_HEADER
### Severity

Critical

### Versions

22.8.1,22.8.2

### Components/Modules

chan_pjsip,res_pjsip_header_funcs

### Operating Environment

Debian 12 (Bookworm) x86_64
[Wazo](https://github.com/wazo-platform/asterisk) 26.03

### Frequency of Occurrence

Frequent

### Issue Description

Deadlock scenario observed in live production environments directly following upgrade to asterisk 22.8.1 (not reproduced on 22.5.2).

- trunk PJSIP endpoints are configured with `set_var = PJSIP_HEADER(add, X-CUSTOMER-ID)=...`
- ARI channel state querying load
- webrtc application clients as well as hardware SIP phone clients

Following is a Claude-based analysis based on logs, ast_coredumper output and asterisk 22.8.1 source code. A patch based on this analysis was found and tested in the live environment where the scenario was first observed (confirmed to fix the deadlock over several days of live production use).

> A deadlock occurs when a PJSIP endpoint is configured with set_var=PJSIP_HEADER(add,X-Header)=value. During channel creation in chan_pjsip_new(), the endpoint's channel
>   variables are set via pbx_builtin_setvar_helper() while the channel lock is held. When the variable name is a dialplan function like PJSIP_HEADER(add,...),
>   func_write_header() calls ast_sip_push_task_wait_serializer(), which blocks synchronously waiting for a PJSIP serializer thread.
> 
>   If a concurrent operation (ARI request, AMI, rtp_check_timeout, etc.) traverses the channels container via ast_channel_get_by_name(), it acquires the container lock then
>   tries to lock individual channels in the iteration callback (by_uniqueid_cb/by_name_cb). If the serializer thread also needs the container lock, a circular dependency
>   forms:
> 
>   Thread A (chan_pjsip_new):  channel_lock → serializer_push_wait (blocks)
>   Thread B (container traversal): container_lock → channel_lock (blocks on Thread A)
>   Serializer thread: needs container_lock → blocks on Thread B
> 
>   This causes a complete Asterisk freeze. In our case, 36 threads were blocked on the container lock, and res_freeze_check triggered SIGABRT after the 30-second timeout.
> 
>   Environment where observed: ~7,300 registered PJSIP endpoints, high concurrent call volume, active ARI integration polling channel variables. Endpoint configured with
>   set_var=PJSIP_HEADER(add,X-CUSTOMER-ID)=${CUSTOMER_ID}.
> 
>   Root cause: In chan_pjsip.c:chan_pjsip_new() (line ~668), the channel_vars loop runs while the channel lock is held. pbx_builtin_setvar_helper() dispatches to
>   ast_func_write() for function-style variable names (names ending with )), which for PJSIP_HEADER leads to func_write_header() doing a synchronous
>   ast_sip_push_task_wait_serializer(). This blocks the thread while holding the channel lock, creating a lock-ordering inversion with any code path that acquires the
>   container lock then individual channel locks.
> 
>   This is related to #307 (same lock-ordering pattern, different triggering function).

Included logs are anonymized excerps from ast_coredumper coredump processing.

 More supporting data could be provided on demand.

Seems similar (in kind) to [#307](https://github.com/asterisk/asterisk/issues/307).  

## Notes

- we did not attempt to reproduce with vanilla asterisk, only with [wazo asterisk build](https://github.com/wazo-platform/asterisk), as part of wazo-platform deployments
- only reproduced in live production environments with enough load
- reproduced in two different clients' production environments (i.e. not specific to a single client's load pattern or environment)

### Relevant log output

[core-asterisk-2026-02-04T11-20-54Z-info-sanitized.txt](https://github.com/user-attachments/files/26799343/core-asterisk-2026-02-04T11-20-54Z-info-sanitized.txt)

```shell
Thread 1158 (Thread 0x7f9e951656c0 (LWP 834925)):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7f9e951606e0) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7f9e951606e0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007f9eb7ca3f7b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7f9e951606e0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f9eb7ca65d8 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f9e95160680, cond=0x7f9e951606b8) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=cond@entry=0x7f9e951606b8, mutex=mutex@entry=0x7f9e95160680) at ./nptl/pthread_cond_wait.c:618
#5  0x000055e7c9d4d7ad in __ast_cond_wait (filename=filename@entry=0x55e7c9eb8ff3 "taskpool.c", lineno=lineno@entry=904, func=func@entry=0x55e7c9eb9380 <__PRETTY_FUNCTION__.4> "__ast_taskpool_serializer_push_wait", cond_name=cond_name@entry=0x55e7c9eb904a "&sync_task.cond", mutex_name=mutex_name@entry=0x55e7c9eb903a "&sync_task.lock", cond=cond@entry=0x7f9e951606b8, t=0x7f9e95160680) at ./main/lock.c:620
#6  0x000055e7c9ddf2cf in __ast_taskpool_serializer_push_wait (serializer=0x55e811437120, task=<optimized out>, data=<optimized out>, file=0x7f9eb2ee9007 "res_pjsip_header_funcs.c", line=<optimized out>, function=0x7f9eb2ee9960 <__PRETTY_FUNCTION__.16> "func_write_header") at ./main/taskpool.c:904
#7  0x00007f9eb2ee71d0 in func_write_header (chan=<optimized out>, cmd=<optimized out>, data=0x7f9e9516080d "add", value=0x7f9e95160970 "XXXXXXXX") at ./res/res_pjsip_header_funcs.c:987
#8  0x000055e7c9d7b5d9 in ast_func_write (chan=chan@entry=0x55e81431da40, function=<optimized out>, value=value@entry=0x7f9e95160970 "XXXXXXXX") at ./main/pbx_functions.c:711
#9  0x000055e7c9d80833 in pbx_builtin_setvar_helper (chan=chan@entry=0x55e81431da40, name=0x55e8010df3d0 "PJSIP_HEADER(add,X-CUSTOMER-ID)", value=0x7f9e95160970 "XXXXXXXX") at ./main/pbx_variables.c:1244
#10 0x00007f9eb2ce6e40 in chan_pjsip_new (session=session@entry=0x55e8017dfb40, state=state@entry=0, exten=exten@entry=0x0, assignedids=assignedids@entry=0x0, requestor=requestor@entry=0x55e808d28e40, cid_name=0x0, title=0x0) at ./channels/chan_pjsip.c:670
#11 0x00007f9eb2ce7a8f in chan_pjsip_request_with_stream_topology (type=<optimized out>, topology=<optimized out>, assignedids=0x0, requestor=0x55e808d28e40, data=0x55e7fc43a134 "+XXXXXXXXXXXX@example_trunk_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", cause=0x7f9e95160e58) at ./channels/chan_pjsip.c:2756
#12 0x000055e7c9cec71c in request_channel (type=0x55e7fc43a128 "PJSIP", request_cap=request_cap@entry=0x0, topology=topology@entry=0x55e81c351f18, assignedids=assignedids@entry=0x0, requestor=requestor@entry=0x55e808d28e40, addr=0x55e7fc43a134 "+XXXXXXXXXXXX@example_trunk_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", cause=0x7f9e95160e58) at ./main/channel.c:6271
#13 0x000055e7c9cece09 in ast_request_with_stream_topology (type=<optimized out>, topology=topology@entry=0x55e81c351f18, assignedids=assignedids@entry=0x0, requestor=requestor@entry=0x55e808d28e40, addr=<optimized out>, cause=cause@entry=0x7f9e95160e58) at ./main/channel.c:6371
#14 0x00007f9eb37f1559 in dial_exec_full (chan=<optimized out>, data=<optimized out>, peerflags=peerflags@entry=0x7f9e95161a00, continue_exec=continue_exec@entry=0x0) at ./apps/app_dial.c:2715
#15 0x00007f9eb37f4846 in dial_exec (chan=<optimized out>, data=<optimized out>) at ./apps/app_dial.c:3483
#16 0x000055e7c9d76dc1 in pbx_exec (c=c@entry=0x55e808d28e40, app=app@entry=0x55e808ca1170, data=data@entry=0x7f9e95162b60 "PJSIP/+XXXXXXXXXXXX@example_trunk_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX,,o(0XXXXXXXXXX)X") at ./main/pbx_app.c:492
#17 0x000055e7c9d6b747 in pbx_extension_helper (c=c@entry=0x55e808d28e40, con=con@entry=0x0, context=0x55e808d29878 "outcall", exten=exten@entry=0x55e808d298c8 "dial", priority=priority@entry=11, label=label@entry=0x0, callerid=<optimized out>, action=<optimized out>, found=<optimized out>, combined_find_spawn=<optimized out>) at ./main/pbx.c:2968
#18 0x000055e7c9d6d46c in ast_spawn_extension (combined_find_spawn=1, found=<optimized out>, callerid=0x55e80685ead0 "+XXXXXXXXXXXX", priority=11, exten=0x55e808d298c8 "dial", context=<optimized out>, c=0x55e808d28e40) at ./main/pbx.c:4223
#19 __ast_pbx_run (c=c@entry=0x55e808d28e40, args=args@entry=0x0) at ./main/pbx.c:4397
#20 0x000055e7c9d6e90b in pbx_thread (data=data@entry=0x55e808d28e40) at ./main/pbx.c:4721
#21 0x000055e7c9df07ed in dummy_start (data=<optimized out>) at ./main/utils.c:1643
#22 0x00007f9eb7ca71f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#23 0x00007f9eb7d278dc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81


Thread 780 (Thread 0x7f9e8e5f96c0 (LWP 816915)):
#0  futex_wait (private=0, expected=2, futex_word=0x55e81431da00) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x55e81431da00, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007f9eb7caa4da in lll_mutex_lock_optimized (mutex=0x55e81431da00) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x55e81431da00) at ./nptl/pthread_mutex_lock.c:128
#4  0x000055e7c9d4d738 in __ast_pthread_mutex_lock (filename=<optimized out>, lineno=lineno@entry=124, func=<optimized out>, mutex_name=mutex_name@entry=0x55e7c9e7ee38 "chan", t=<optimized out>) at ./main/lock.c:358
#5  0x000055e7c9cb0679 in __ao2_lock (user_data=user_data@entry=0x55e81431da40, lock_how=lock_how@entry=AO2_LOCK_REQ_MUTEX, file=file@entry=0x55e7c9e8e623 "channelstorage_ao2_legacy.c", func=func@entry=0x55e7c9e8e810 <__PRETTY_FUNCTION__.7> "by_uniqueid_cb", line=line@entry=124, var=var@entry=0x55e7c9e7ee38 "chan") at ./main/astobj2.c:241
#6  0x000055e7c9d0286b in by_uniqueid_cb (obj=0x55e81431da40, arg=arg@entry=0x55e8179551ea, data=data@entry=0x7f9e8e5f69c8, flags=flags@entry=0) at ./main/channelstorage_ao2_legacy.c:124
#7  0x000055e7c9cb243d in internal_ao2_traverse (self=0x55e7f97ce840, flags=flags@entry=OBJ_SEARCH_NONE, cb_fn=cb_fn@entry=0x55e7c9d027f0 <by_uniqueid_cb>, arg=arg@entry=0x55e8179551ea, data=data@entry=0x7f9e8e5f69c8, type=type@entry=AO2_CALLBACK_WITH_DATA, tag=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>) at ./main/astobj2_container.c:326
#8  0x000055e7c9cb28ce in __ao2_callback_data (c=<optimized out>, flags=flags@entry=OBJ_SEARCH_NONE, cb_fn=cb_fn@entry=0x55e7c9d027f0 <by_uniqueid_cb>, arg=arg@entry=0x55e8179551ea, data=data@entry=0x7f9e8e5f69c8, tag=tag@entry=0x0, file=0x55e7c9e8e623 "channelstorage_ao2_legacy.c", line=69, func=0x55e7c9e8e800 <__PRETTY_FUNCTION__.6> "callback") at ./main/astobj2_container.c:421
#9  0x000055e7c9d03158 in callback (rdlock=<optimized out>, ao2_flags=0, data=0x7f9e8e5f69c8, arg=0x55e8179551ea, cb_fn=0x55e7c9d027f0 <by_uniqueid_cb>, driver=0x55e7f9542f20) at ./main/channelstorage_ao2_legacy.c:69
#10 get_by_name_prefix (driver=0x55e7f9542f20, name=0x55e8179551ea "1770201082.11016", name_len=<optimized out>, lock=<optimized out>) at ./main/channelstorage_ao2_legacy.c:242
#11 0x00007f9eb2b6288b in ast_ari_channels_get_channel_var (headers=headers@entry=0x55e821e5e3f0, args=args@entry=0x7f9e8e5f6a40, response=response@entry=0x7f9e8e5f6c30) at ari/resource_channels.c:1523
#12 0x00007f9eb2b5e3f0 in ast_ari_channels_get_channel_var_cb (ser=<optimized out>, get_params=<optimized out>, path_vars=<optimized out>, headers=0x55e821e5e3f0, body=0x0, response=0x7f9e8e5f6c30) at ./res/res_ari_channels.c:2438
#13 0x00007f9eb2c70a98 in ast_ari_invoke (ser=ser@entry=0x55e806f7c6d0, source=source@entry=ARI_INVOKE_SOURCE_REST, urih=urih@entry=0x7f9eb2c8c0c0 <http_uri>, uri=uri@entry=0x7f9e8e5f6cf9 "channels/1770201082.11016/variable", method=method@entry=AST_HTTP_GET, get_params=get_params@entry=0x55e810a797c0, headers=<optimized out>, body=<optimized out>, response=<optimized out>) at ./res/res_ari.c:711
#14 0x00007f9eb2c71c94 in ast_ari_callback (ser=0x55e806f7c6d0, urih=0x7f9eb2c8c0c0 <http_uri>, uri=0x7f9e8e5f6cf9 "channels/1770201082.11016/variable", method=AST_HTTP_GET, get_params=0x55e810a797c0, headers=0x55e821e5e3f0) at ./res/res_ari.c:1062
#15 0x000055e7c9e33aa0 in handle_uri (headers=<optimized out>, method=AST_HTTP_GET, uri=0x7f9e8e5f6cf9 "channels/1770201082.11016/variable", ser=0x55e806f7c6d0) at ./main/http.c:1519
#16 httpd_process_request (ser=ser@entry=0x55e806f7c6d0) at ./main/http.c:2005
#17 0x000055e7c9e33ea3 in httpd_helper_thread (data=0x55e806f7c6d0) at ./main/http.c:2068
#18 0x000055e7c9df07ed in dummy_start (data=<optimized out>) at ./main/utils.c:1643
#19 0x00007f9eb7ca71f5 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#20 0x00007f9eb7d278dc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Asterisk 22.8.1-1~wazo1.deb12 built by builder @ 15313e768200 on a x86_64 running Linux on 2026-01-29 15:25:12 UTC

System started: 2026-02-03 23:51:37.161033
Last reload: 2026-02-04 09:41:49.717732


TaskProcessors (12541):
  pjsip/options taskprocessors: 7293
  pjsip/mwi taskprocessors: 8 (all exceeded high water mark)
Bridges (30):
Channels (87):
```

### Asterisk Issue Guidelines

- [x] Yes, I have read the Asterisk Issue Guidelines

### PR DESCRIPTION
**Pull request by DrPyser**
When a PJSIP endpoint is configured with set_var invoking a dialplan
function (e.g. PJSIP_HEADER(add,...)), chan_pjsip_new() calls
pbx_builtin_setvar_helper() while holding the channel lock.
For function-style variables, this dispatches to ast_func_write()
which, in the case of PJSIP_HEADER, calls
ast_sip_push_task_wait_serializer() -- blocking synchronously while
the channel lock is held.

If a concurrent operation (ARI, AMI, rtp_check_timeout) traverses
the channels container via ast_channel_get_by_name(), it acquires
the container lock then tries to lock individual channels in the
iteration callback (by_uniqueid_cb/by_name_cb). When the serializer
thread also needs the container lock, a circular dependency forms:

  channel_lock -> serializer_wait -> container_lock -> channel_lock

This causes a complete Asterisk freeze. In the observed case, 36
threads were blocked on the container lock until res_freeze_check
triggered SIGABRT after its 30-second timeout.

Unlock the channel before iterating endpoint channel_vars so that
dialplan functions can block without holding the channel lock. Re-lock
the channel for ast_channel_stage_snapshot_done() so the batched
snapshot is published under lock and captures the full channel state
including the variables set during the loop.

Fixes: https://github.com/asterisk/asterisk/issues/1872

### CODE REVIEW

**Comment by DrPyser** [comment]
cherry-pick-to: 20
cherry-pick-to: 22
cherry-pick-to: 23

**Comment by DrPyser** [comment]
For context, the original deadlock observation was in February. it was since reproduced in another production environment of a different client.

The scenario was reported and discussed in asterisk-dev mailling list, where the analysis and patch was discussed.

The analysis is largely Claude-driven (not a C or Asterisk expert myself), but challenged and independently reproduced from deadlock scenarios in two different client environments.

The scenario requiring some high load and some specific load patterns, we were not able to reproduce artificially or construct a "minimal reproduction scenario" on vanilla asterisk.

**Comment by gtjoseph** [comment]
> Workflow Check failed [master-pjs5](https://github.com/asterisk/asterisk/actions/runs/24532524955/job/71720204206): FAILED TEST: channels/pjsip/subscriptions/rls/lists_of_lists/nominal/mwi/batched

It's a timing dependent test that fails more often than not because of GitHub's overworked virtualization platform.  Don't worry about it.

Do worry about the PR checklist items however :)

**Comment by gtjoseph** [comment]
and for future reference, the 3 active branches that need cherry-picks are 20, 22 and 23.

File: channels/chan_pjsip.c [hunk 1]
```diff
@@ -665,12 +665,15 @@ static struct ast_channel *chan_pjsip_new(struct ast_sip_session *session, int s
 		ast_channel_zone_set(chan, zone);
 	}
 
+	ast_channel_unlock(chan);
```
Comment (jcolp) [inline channels/chan_pjsip.c:669]: The pbx_builtin_setvar_helper doesn't actually contribute to the snapshot, so instead call ast_channel_stage_snapshot_done, unlock, and do the pbx_builtin_setvar_helper, and don't lock/unlock again.

**Review by jcolp — CHANGES_REQUESTED** [review]

**Review by jcolp — APPROVED** [review]

**Comment by DrPyser** [comment]
@jcolp thanks for merging this. I may not have been dilligent enough before pushing the commit change though.

 I forgot to correct the commit message around the `ast_stage_snapshot_done` usage. The message may be misleading, but I guess now that it's merged it may not be worth amending?

Also, `pbx_builtin_setvar_helper` does call `ast_channel_publish_varset` which calls `ast_channel_publish_snapshot` when `ast_channel_has_manager_vars`.

https://github.com/asterisk/asterisk/blob/f616affc2af658fd5149374e10efcb23081339b1/main/pbx_variables.c#L1273-L1278

https://github.com/asterisk/asterisk/blob/f616affc2af658fd5149374e10efcb23081339b1/main/stasis_channels.c#L1221-L1224

So a side effect of the patch as merged would be that if the variables used in set_var  are configured as manager vars, a new snapshot would be created and published for each pbx_builtin_setvar_helper call?

If you think that's worth fixing, I can resubmit a new PR.

Thanks for the follow up either way!

**Comment by jcolp** [comment]
It can't be amended. We do not rewrite history of the repo.

As for manager vars, good catch. I think you are correct. Practically speaking it probably wouldn't have too much of an impact these days so I think it's fine to leave it.
