### PR TITLE
app_voicemail_odbc: fix msgnum race and crash on failed STORE

### LINKED ISSUE #1653: [bug]: Asterisk ODBC Voicemail Crash Caused by Voicemail Re-entry Loop and Unsafe BLOB Retrieval
### Severity

Trivial

### Versions

20.16.0

### Components/Modules

odbc mv

### Operating Environment

centos 9

### Frequency of Occurrence

Occasional

### Issue Description

A dialplan loop repeatedly re-enters voicemail for the same call, triggering multiple ODBC voicemail notifications; during repeated retrieval of the recording LONGBLOB via SQLGetData, the MySQL ODBC driver crashes, causing Asterisk to terminate.

[core-asterisk-2025-12-13T05-10-28Z-brief.txt](https://github.com/user-attachments/files/24147947/core-asterisk-2025-12-13T05-10-28Z-brief.txt)
[core-asterisk-2025-12-13T05-10-28Z-full.txt](https://github.com/user-attachments/files/24147946/core-asterisk-2025-12-13T05-10-28Z-full.txt)
[core-asterisk-2025-12-13T05-10-28Z-info.txt](https://github.com/user-attachments/files/24147949/core-asterisk-2025-12-13T05-10-28Z-info.txt)
[core-asterisk-2025-12-13T05-10-28Z-locks.txt](https://github.com/user-attachments/files/24147948/core-asterisk-2025-12-13T05-10-28Z-locks.txt)
[core-asterisk-2025-12-13T05-10-28Z-thread1.txt](https://github.com/user-attachments/files/24147945/core-asterisk-2025-12-13T05-10-28Z-thread1.txt)

### Relevant log output

```shell

```

### Asterisk Issue Guidelines

- [x] Yes, I have read the Asterisk Issue Guidelines

### PR DESCRIPTION
**Pull request by phoneben**
app_voicemail_odbc: fix msgnum race and crash on failed STORE

Two concurrent callers leaving voicemail to the same mailbox could be assigned the same msgnum because ast_unlock_path() was called before STORE(), allowing a second thread to read the same LAST_MSG_INDEX() before the first INSERT committed. The losing thread got a duplicate key error, but execution continued into notify_new_message() -> RETRIEVE() because the STORE() return value was not checked. RETRIEVE() then fetched the winning thread's DB row, mmap'd its blob size against the locally truncated file, and crashed with SIGBUS.

Hold the path lock through STORE() and bail out on failure.

Fixes: #1653

### CODE REVIEW

**Comment by phoneben** [comment]
cherry-pick-to: 20
cherry-pick-to: 22
cherry-pick-to: 23

**Comment by phoneben** [comment]
ai used

**Comment by phoneben** [comment]
> Workflow Check failed [master-app_dial](https://github.com/asterisk/asterisk/actions/runs/24212385781/job/70685401604): FAILED TEST: apps/queues/transfer/caller_attended

can not see why this failed did not touch this at all

**Comment by gtjoseph** [comment]
> > Workflow Check failed [master-app_dial](https://github.com/asterisk/asterisk/actions/runs/24212385781/job/70685401604): FAILED TEST: apps/queues/transfer/caller_attended
> 
> can not see why this failed did not touch this at all

Don't worry about it.  Transfer tests are always a bit flakey because they're timing dependent and the GitHub runners aren't exactly consistent when it comes to resource allocation.

File: apps/app_voicemail.c [hunk 1]
```diff
@@ -7483,16 +7483,35 @@ static int leave_voicemail(struct ast_channel *chan, char *ext, struct leave_vm_
...
 					}
 					/* We must store the file first, before copying the message, because
 					 * ODBC storage does the entire copy with SQL.
+					 * Hold the path lock until after STORE so that concurrent callers
+					 * cannot read the same LAST_MSG_INDEX before the INSERT is committed.
 					 */
 					if (ast_fileexists(fn, NULL, NULL) > 0) {
-						SCOPE_CALL(-1, STORE, dir, vmu->mailbox, vmu->context, msgnum, chan, vmu, fmt, duration, vms, flag, msg_id);
+#ifdef ODBC_STORAGE
+					int store_failed;
```
Comment (jcolp) [inline apps/app_voicemail.c]: The indentation here is messed up and not indented enough.

**Review by jcolp — CHANGES_REQUESTED** [review]

**Review by jcolp — APPROVED** [review]
