### PR TITLE
dnsmgr.c: dnsmgr_refresh() incorrectly flags change with DNS round-robin

### LINKED ISSUE #924: [bug]: dnsmgr.c: dnsmgr_refresh() should not flag change if IP address order changes
### Severity

Minor

### Versions

20.9.3

### Components/Modules

asterisk

### Operating Environment

Debian 12

### Frequency of Occurrence

Constant

### Issue Description

On my [AllStarLink asterisk + app_rpt] system I noticed many log messages suggesting that an IP address was periodically being updated.

Researching the log messages I found that the dnsmgr_refresh() function checks to see if the IP address associated with a name/service has changed.  The gotcha is that the ast_get_ip_or_srv() function only returns the first IP address returned by the DNS query. If there are multiple IPs associated with the name and the returned order is not consistent (e.g. with DNS round-robin) then the other IP addresses are not included in the comparison and the entry is flagged as changed even though the IP is still valid.

Is it a big deal to switch addresses? Probably not, but it's likely triggering extra/unneeded work.

Also, with each change being logged the messages stand out on a generally quiet system.

### Relevant log output

```shell
[2024-09-29 12:10:02.677] NOTICE[836] dnsmgr.c: dnssrv: host 'register.allstarlink.org' changed from 34.105.111.212:443 to 162.248.92.131:443
[2024-09-29 12:20:02.720] NOTICE[836] dnsmgr.c: dnssrv: host 'register.allstarlink.org' changed from 162.248.92.131:443 to 34.105.111.212:443
[2024-09-29 12:40:02.680] NOTICE[836] dnsmgr.c: dnssrv: host 'register.allstarlink.org' changed from 34.105.111.212:443 to 162.248.92.131:443
[2024-09-29 13:00:02.678] NOTICE[836] dnsmgr.c: dnssrv: host 'register.allstarlink.org' changed from 162.248.92.131:443 to 34.105.111.212:443
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

### PR DESCRIPTION
**Pull request by Allan-N**
The dnsmgr_refresh() function checks to see if the IP address associated with a name/service has changed. The gotcha is that the ast_get_ip_or_srv() function only returns the first IP address returned by the DNS query. If there are multiple IPs associated with the name and the returned order is not consistent (e.g. with DNS round-robin) then the other IP addresses are not included in the comparison and the entry is flagged as changed even though the IP is still valid.

Updated the code to check all IP addresses and flag a change only if the original IP is no longer valid.

Resolves #924

### CODE REVIEW

**Comment by Allan-N** [comment]
This change resolves Issue https://github.com/asterisk/asterisk/issues/924

File: include/asterisk/acl.h [hunk 1]
```diff
@@ -287,6 +287,32 @@ int ast_get_ip(struct ast_sockaddr *addr, const char *hostname);
...
+ * then this function acts exactly like a call to ast_get_ip.
+ *
+ * \param addr The IP address found.  The address family is used
+ * as an input parameter to filter the returned addresses.  If
+ * it is 0, both IPv4 and IPv6 addresses can be returned.
+ *
+ * \param hostname The hostname to look up
+ * \param service A specific service provided by the host. A NULL service results
+ * in an A-record lookup instead of an SRV lookup
+ * \param preference The preferred IP address to return.  If multiple results
```
Comment (jcolp) [inline include/asterisk/acl.h:307]: I don't think this description is comprehensive enough. For example, what happens if the preferred IP address is not present in the results?

File: main/acl.c [hunk 2]
```diff
@@ -872,18 +872,29 @@ enum ast_acl_sense ast_apply_ha(const struct ast_ha *ha, const struct ast_sockad
...
 {
 	struct ast_sockaddr *addrs;
 	int addrs_cnt;
 
 	addrs_cnt = ast_sockaddr_resolve(&addrs, name, flag, family);
 	if (addrs_cnt > 0) {
-		if (addrs_cnt > 1) {
+		struct ast_sockaddr *resolved = &addrs[0];
+
+		if (preference != NULL) {
```
Comment (jcolp) [inline main/acl.c:885]: We just use if (preference) { in our coding guidelines

**Review by jcolp — CHANGES_REQUESTED** [review]

File: include/asterisk/acl.h (hunk 1 above)
Comment (Allan-N) [reply include/asterisk/acl.h]: Updated

File: main/acl.c (hunk 2 above)
Comment (Allan-N) [reply main/acl.c]: Updated

**Comment by jcolp** [comment]
There should be a single commit for this:

https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/?h=github#address-review-comments-and-test-failures

**Review by jcolp — DISMISSED** [review]

**Review by gtjoseph — CHANGES_REQUESTED** [review]
Please change the last line in the commit message that has the issue number as follows or the release change log won't pick it up.
```
Resolves: #924
```


That line also must appear in the pull request description, not a separate comment or GitHub won't automatically close the issue when the PR merges.  You can edit the description by clicking on the `...` at the top of the first comment and selecting `Edit`.


https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/

**Review by jcolp — APPROVED** [review]

**Review by gtjoseph — COMMENTED** [review]
For future reference, you need a colon (`:`) after `Resolves` to trigger the change log automation.  If you have time to fix it, great, otherwise the release change log won't list this issue as being closed in the summary.  Up to you.

**Comment by Allan-N** [comment]
Automation is good :-)

**Review by gtjoseph — APPROVED** [review]
Thanks!

**Comment by Allan-N** [comment]
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22
